#******************************************************************************#
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: fcarranz <fcarranz@student.42barcel>       +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/08/20 09:36:54 by fcarranz          #+#    #+#              #
#    Updated: 2024/08/20 09:50:49 by fcarranz         ###   ########.fr        #
#                                                                              #
#******************************************************************************#

NAME = philo
CC = gcc
CFLAGS = -Wall -Wextra -Werror -g

.PHONY: all clean fclean re

all: $(NAME)

clean:
	rm -f $(NAME)

fclean: clean

re: fclean all